### ISSUE TITLE
"Fetch failed" after NodeRed upgrade?

### ISSUE THREAD

**Issue by andrepferreira** [nileio/node-red-contrib-ccxt-v2#14]
Hi there

I recently had a HDD failure and decided to install the latest version of Node Red on reinstall. I am now getting an error as below when trying to access Bitstamp APIs. Node Red is now running ver 3.0.2.

The error pops up immediately, almost like the module is not even making the request. I did also test with a raw http GET on Node Red to a public API and that works.

"bitstamp GET https://www.bitstamp.net/api/v2/trading-pairs-info/  fetch failed"

Anyone else seeing this?

Thanks

**Comment by nileio** [comment]
@andrepferreira the node is not tested with ver 3.
I'll have a look

**Comment by andrepferreira** [comment]
Thanks @nileio, much appreciated!

**Comment by nileio** [comment]
@andrepferreira it works Ok with Bitstamp , even on ver 3.0.2
what is the nodejs version ?
``` node -v ```

**Comment by nileio** [comment]
an upgrade is pushed to npm - please use the latest version (v0.2.12) and report back if you still face issues

**Comment by andrepferreira** [comment]
Hi @nileio, thanks. I'm using nodejs version v18.10.0 and Ubuntu 22.04.1. I updated the node, but still no luck. Same error. I have tried the Exchange and Unified APIs. I'm using the Bitstamp v2 option, but also tried the Bitstamp1 with the same error. 

Could you maybe share a flow you are using that I could test on my side? 

I'm trying a simple "fetchBalance" for {"pair":"btcusd"} with the Exchange API to eliminate any auth problems for now. If I use the url returned in the error (https://www.bitstamp.net/api/v2/ticker/btcusd/) via a standard http request node, I get the expected response from Bitstamp. I must be doing something simple wrong here, but just can't find it.

**Comment by nileio** [comment]
nodejs v18 is not tested , only v14 - v16. I suspect this is the problem. 
please downgrade your nodejs to v16 and ensure this is the one being used and try again..

**Comment by andrepferreira** [comment]
Hi @nileio, thanks! That was indeed the issue. I have downgraded and all is working fine again. Thanks again for you help, much appreciated!
