### ISSUE TITLE
Implement the done event

### ISSUE THREAD

**Issue by bolobox** [nileio/node-red-contrib-ccxt-v2#15]
Hello!

I have noticed that the complete node does not get fired when cctx node have finished its task.

This is due the code does not use [done()](https://nodered.org/blog/2019/09/20/node-done) when the execution is finished.

It will be very usefull to have this feature added.

Thanks

**Comment by nileio** [comment]
thanks for the note - this can be done. it should be an easy fix.. will get to it soon

**Comment by bolobox** [comment]
thanks @nileio ! 

BTW, you have created an amazing component for nodered ;)

**Comment by nileio** [comment]
@bolobox thanks - pls update the node and use the latest version now and report back if the issue is not fixed.
stay tuned, I have a major project going on that I hope to publish soon
