### ISSUE TITLE
incompatibility with node-red 3.1.0

### ISSUE THREAD

**Issue by campinzon** [nileio/node-red-contrib-ccxt-v2#16]
This version does not work with node version 18, is it possible to facilitate its use in the current version of node-red 3.1.0 ?

npm WARN config production Use `--omit=dev` instead.
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: node-red-contrib-ccxt-v2@0.2.13
npm ERR! notsup Not compatible with your version of node/npm: node-red-contrib-ccxt-v2@0.2.13
npm ERR! notsup Required: {"node":">=14.0.0 <=16"}
npm ERR! notsup Actual:   {"npm":"10.2.3","node":"v18.19.0"}

npm ERR! A complete log of this run can be found in: /home/carlos/.npm/_logs/2023-12-04T20_40_48_911Z-debug-0.log

regards!

**Comment by nileio** [comment]
@campinzon sorry for late response ! I didnt notice the issue. in fact the module already supports version 18 I pushed a new update with updates to nodejs compatability

**Comment by nileio** [comment]
pushed to Node-RED library
