### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by noobydp** [nileio/node-red-contrib-ccxt-v2#2]
Howdy,
Would you be able to publish to npm to make it easier to install?

I manually installed the module and it works well (for what I need at least), but I keep losing the module when I update my docker container that runs nodered.

Thanks

**Comment by nileio** [comment]
@noobydp thanks for note. 
Yes will do , just waiting to integrate few changes then will push to npm.

**Comment by noobydp** [comment]
Hey @nileio any chance you could publish to npm as is?

My manual install keeps getting messed up when I update my docker container.

**Comment by nileio** [comment]
@noobydp really sorry for the delay - been flat out. pushed to npm and node-red library.
please try and feel free to get back with any questions!

**Comment by nileio** [comment]
@noobydp https://flows.nodered.org/node/node-red-contrib-ccxt-v2
