### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by cnoork** [nileio/node-red-contrib-ccxt-v2#4]
I am running node-red in a docker container and get the follwing error:

> bash-5.0$ npm install node-red-contrib-ccxt-v2 --save
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/node-red-contrib-ccxt-v2 - Not found
> npm ERR! 404
> npm ERR! 404  'node-red-contrib-ccxt-v2@latest' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /usr/src/node-red/.npm/_logs/2021-05-11T16_29_49_716Z-debug.log
> bash-5.0$ cat  /usr/src/node-red/.npm/_logs/2021-05-11T16_29_49_716Z-debug.log
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'install',
> 1 verbose cli   'node-red-contrib-ccxt-v2',
> 1 verbose cli   '--save' ]
> 2 info using npm@6.14.10
> 3 info using node@v10.23.1
> 4 verbose config Skipping project config: /usr/src/node-red/.npmrc. (matches userconfig)
> 5 verbose npm-session bf17e86e0429dc9e
> 6 silly install loadCurrentTree
> 7 silly install readLocalPackageData
> 8 http fetch GET 404 https://registry.npmjs.org/node-red-contrib-ccxt-v2 184ms
> 9 http fetch GET 404 https://registry.npmjs.org/node-red-contrib-ccxt-v2 50ms
> 10 silly fetchPackageMetaData error for node-red-contrib-ccxt-v2@latest 404 Not Found - GET https://registry.npmjs.org/node-red-contrib-ccxt-v2 - Not found
> 11 timing stage:rollbackFailedOptional Completed in 1ms
> 12 timing stage:runTopLevelLifecycles Completed in 1316ms
> 13 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/node-red-contrib-ccxt-v2 - Not found
> 13 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15)
> 13 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
> 14 verbose statusCode 404
> 15 verbose pkgid node-red-contrib-ccxt-v2@latest
> 16 verbose cwd /usr/src/node-red
> 17 verbose Linux 4.4.59+
> 18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-red-contrib-ccxt-v2" "--save"
> 19 verbose node v10.23.1
> 20 verbose npm  v6.14.10
> 21 error code E404
> 22 error 404 Not Found - GET https://registry.npmjs.org/node-red-contrib-ccxt-v2 - Not found
> 23 error 404
> 24 error 404 'node-red-contrib-ccxt-v2@latest' is not in the npm registry.
> 25 error 404 You should bug the author to publish it (or use the name yourself!)
> 26 error 404 Note that you can also install from a
> 27 error 404 tarball, folder, http url, or git url.
> 28 verbose exit [ 1, true ]

My goal is to get the crypto balance from KuCoin, with masalinas verion I get a error with password and have no idea where to place that and hope this one does support KuCoin or has the option to add the extra security.

With kind regards,
Chris

**Comment by cnoork** [comment]
Did fount a mistake from my side to start the installation before I downloaded the package, but un fortunately it did not solve my installation issue.

**Comment by nileio** [comment]
@cnoork the package is not pushed to npm .. you can clone the repo and install in node-red home directory.
really have been behind with this node. i just merged a long due PR which needs additional work too.. feel free to contrib

**Comment by cnoork** [comment]
Thak you @nileio for the help, I have managed to install it in the docker container by copy the whole directory in /data/node_modules (/data is not part from the docker image and should work even after an update from the container)

I hit only now against a next small issue. I can't select an exchange ("No results found") and have a small broken icon with the message "retrieving data..." which is not disappearing. Does someone have a suggestion where to look?

**Comment by nileio** [comment]
@cnoork I am pushing the updated node to npm .. so should be available in the next hour in the pallette.
please give that version and a go and let me know

**Comment by nileio** [comment]
@cnoork pls try the node-red version https://flows.nodered.org/node/node-red-contrib-ccxt-v2

**Comment by cnoork** [comment]
@nileio thank you very much, I am successful to install and connect to KuCoin and can now build my reports.
