### ISSUE TITLE
Failed to request private queries for Binance.com

### ISSUE THREAD

**Issue by cnoork** [nileio/node-red-contrib-ccxt-v2#6]
I successfully get all information from different crypto brokers but for Binance I get only the public part. For the private part I get the following error:

> binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: xx.yy.zz.158"}

I have also the palette node-red-contrib-binance installed and that one is working with the same credentials, what is going wrong in my Node Red

**Comment by nileio** [comment]
@cnoork hmm on the API keys config, when you open it does it show the exchange in the dropdown menu as 'Binance'? have you tried using BinanceUS?

**Comment by nileio** [comment]
looks like the list does not list the exchange correctly in the config , will push out a fix first

**Comment by nileio** [comment]
@cnoork thanks for reporting. i pushed a fix that should solve it. the menu should actually list name of the exchange. please try and report back. Please update the node and try again

**Comment by cnoork** [comment]
@nileio thank you for the update, it is now working for binance. I am happy and can now go on with my flows...
