### ISSUE TITLE
I don't get results for query on my open orders for KuCoins

### ISSUE THREAD

**Issue by cnoork** [nileio/node-red-contrib-ccxt-v2#7]
The connection is working to get coin balance by "get_accounts" but unfortunately I am not successful to get my open orders by the option "get_orders". Do I use a wrong option or is there something else what I need to do?

**Comment by nileio** [comment]
@cnoork what message or error do you receive ? are u using exchange specific APIs?

**Comment by cnoork** [comment]
Hi @nileio, I get a normal response only without content.

Here is the result:
{"exchange":"KuCoin","api":"get_fills","arguments":"","payload":{"code":"200000","data":{"currentPage":"1","pageSize":"50","totalNum":"0","totalPage":"0","items":[]}}}

**Comment by nileio** [comment]
@cnoork have you tried using Unified API instead ? Do you get empty results with that too?

**Comment by nileio** [comment]
@cnoork can i close this issue now?

**Comment by cnoork** [comment]
I didn't work before with the Unified API, but when I select that option for KuCoins I have only the option "loadMarkets". When I look to the other brokers I see much more options to select from.

**Comment by nileio** [comment]
@cnoork a screenshot will be of great help.. please provide a screen shot of what you see in both Unified and Custom APIs.
`Unified API` should be the first thing to use actually! If this does not give all what is needed, then the custom APIs can be used. I mean providing access to the exchange-specific API is an advanced feature really. we need to look into why this exchange

**Comment by cnoork** [comment]
Thanks for your response. Here the screenshot from what I can select in the pull down menu, for "Exchange API" the list is way longer than I can snapshot.
![2021-09-19 17_47_34-Node-RED _ 192 168 10 10](https://user-images.githubusercontent.com/17862084/133934010-ca619fed-298b-4054-b41a-e4cb44384d89.jpg)
![2021-09-19 17_49_35-Node-RED _ 192 168 10 10](https://user-images.githubusercontent.com/17862084/133934013-bbae018c-d4be-4388-bfa9-67f62d6a4e03.jpg)

**Comment by nileio** [comment]
you should be able to see list of APIs under `Unified API` list for Kucoin exchange now. Please try the Unified API before using `Exchange API` .. If you have still other issues , please open a new issue
