### ISSUE TITLE
Bitstamp API version being used?

### ISSUE THREAD

**Issue by andrepferreira** [nileio/node-red-contrib-ccxt-v2#8]
Hi @nileio, just a question. 

I received a mail from bitstamp informing me they are depreciating the v1.0 of their API in favour of v2.0.

Is your bitstamp implementation done on v1 or v2? Specifically the Unified API?

Thanks

**Comment by nileio** [comment]
@andrepferreira it is using ccxt version 1.47 or later. https://github.com/ccxt/ccxt/blob/master/js/bitstamp.js
it should be compatible with latest APIs or you may find two exchanges which comply with differenet apis. check ccxt docs.

**Comment by andrepferreira** [comment]
Hi @nileio, thank for the reply. There are in fact two bitstamp exchanges listed, one specifically for the old v1 API.

Thanks!
