### ISSUE TITLE
Support Sandbox Mode

### ISSUE THREAD

**Issue by Borfswitch** [nileio/node-red-contrib-ccxt-v2#9]
It would be great if there was an option to turn on sandbox mode.

```
const exchange = new ccxt.binance (config)
exchange.setSandboxMode (true) // enable sandbox mode
```

**Comment by Borfswitch** [comment]
I tried setting the url for my api key to 'test' but it kept resetting to 'api'.

![image](https://user-images.githubusercontent.com/6481864/132922102-13f1805c-1958-4e57-96a3-f6e4d70e1257.png)

**Comment by nileio** [comment]
@Borfswitch please clarify what is sandbox mode and what is used for ? I am not familiar with it.. 
if the is reseting from test to api , we need to look into that. It should save the config and get used in the call.

**Comment by Borfswitch** [comment]
Here’s a link to the docs on sandbox mode: https://ccxt.readthedocs.io/en/latest/manual.html?highlight=Sandbox#testnets-and-sandbox-environments

I’ve been using sandbox mode to hit the testnet version of the exchange api I’m using. 

I’m guessing that setting the url for the api secret to ‘test’ would accomplish the same thing, but when I try that it seems to always reset back to ‘api’, and the url starts resolving to `[object object]`

I have only tried this with Phemex so far.

**Comment by Borfswitch** [comment]
I wonder if the input can't handle the url value if it's an object?

Phemex urls:
```
            'urls': {
                'logo': 'https://user-images.githubusercontent.com/1294454/85225056-221eb600-b3d7-11ea-930d-564d2690e3f6.jpg',
                'test': {
                    'v1': 'https://testnet-api.phemex.com/v1',
                    'public': 'https://testnet-api.phemex.com/exchange/public',
                    'private': 'https://testnet-api.phemex.com',
                },
                'api': {
                    'v1': 'https://{hostname}/v1',
                    'public': 'https://{hostname}/exchange/public',
                    'private': 'https://{hostname}',
                },
                'www': 'https://phemex.com',
                'doc': 'https://github.com/phemex/phemex-api-docs',
                'fees': 'https://phemex.com/fees-conditions',
                'referral': {
                    'url': 'https://phemex.com/register?referralCode=EDNVJ',
                    'discount': 0.1,
                },
            },
```

https://github.com/nileio/node-red-contrib-ccxt-v2/blob/61f1547aaf848dbf73cf405473a47e4f51597b00/ccxt-v2/ccxt-api.html#L1832
```
          $.getJSON(
            "ccxt-v2/exchangeurls",
            {
              exchange: exchange
            },
            function (result) {
              $("#node-config-input-url").empty();
              $("#node-config-input-url").append(
                $("<option />")
                  .val("default")
                  .text("Default")
              );
              $.each(result.exchangeurls, function (key, value) {
                $("#node-config-input-url").append(
                  $("<option />")
                    .val(value[1])
                    .text(value[0])
                );
                $("#node-config-input-url").val(config.url);
                $("#node-config-input-url").trigger("change");
              });
            }
          ).error(function (error) {
            console.log(error);
          });
```

**Comment by Borfswitch** [comment]
Maybe related to this section?

https://github.com/nileio/node-red-contrib-ccxt-v2/blob/61f1547aaf848dbf73cf405473a47e4f51597b00/ccxt-v2/ccxt-api.js#L490-L496

**Comment by nileio** [comment]
@Borfswitch thanks for the update. I will look into the fix.
Yes the `URL` field should be used for that purpose. If you choose `test` it should use the testnet environment for that exchange, and `default` is usually the livenet. those are populated from `ccxt`. 
If we fix this , this may negate the need for your new field. 
there are some exchanges which dont usually comply with the ccxt structure and cause issues like that. i will check it later

**Comment by nileio** [comment]
@Borfswitch the `URL` field is not a reliable solution unfortunately. There are too many variations out there for exchanges. 
I am thinking of dropping this field altogether in favor of your `sandbox` mode field. I didn't know it existed. The reason `URL` field was there is only so people can choose different environment, however, truly this is only useful for different environments only, that is either livenet, or testnet. I dont know of any exchange which may provide other types of environments. 
but if this is only a matter of either `default` being the livenet, and using the new field `sandbox` mode, then we dont need the `URL` field. thoughts?
it will be a breaking change however we I see it will be a better solution

**Comment by Borfswitch** [comment]
@nileio I agree, I think sandbox mode is a better solution.

However, I also discovered that not all exchanges support test mode. It would be best to hide the option for exchanges that do not support sandbox mode. I will look into whether ccxt has a way to check if it’s supported for each exchange. 

I can also remove the url input field as part of my pull request.

**Comment by Borfswitch** [comment]
@nileio I pushed an update to my pull request. 

I also found a way to check for sandbox mode support the same way CCXT does it:
https://github.com/ccxt/ccxt/blob/b0f98f4fcdc5799a12ac076fe5a3a0b701beb443/js/base/Exchange.js#L449-L469

Using that I was able to set the sandbox mode option to hidden for exchanges that do not have 'test' urls.

**Comment by nileio** [comment]
I'll check thanks. Does this then negate the need for the field `URL` altogether? I am keen to remove it as it's bringing no use in this context then..

**Comment by Borfswitch** [comment]
@nileio Yes. 

I went ahead and removed the url field altogether in my pull request.
